// lib/config/portfolio.ts

export interface PortfolioProject {
  id: number;
  slug: string;
  title: string;
  category: 'marketing' | 'web' | 'music' | 'video';
  categoryLabelAr: string;
  categoryLabelFr: string;
  categoryLabelEn: string;
  img: string;
  tags: string[];
  highlightAr: string;
  highlightFr: string;
  highlightEn: string;
  metrics?: string;
  publishedAt: string;
}

export const portfolioProjects: PortfolioProject[] = [
  {
    id: 20,
    slug: 'decoafrica',
    title: 'Decoafrica',
    category: 'marketing',
    categoryLabelAr: 'تسويق وحضور رقمي',
    categoryLabelFr: 'Marketing & Présence Digitale',
    categoryLabelEn: 'Marketing & Digital Presence',
    img: '/assets/agency/decoafrica.jpg',
    tags: ['Digital Strategy', 'Branding', 'Advertising', 'Social Media'],
    highlightAr: 'حضور رقمي متكامل لعلامة نباتات وديكور منزلي، وحملات ممولة رفعت المبيعات بشكل قياسي.',
    highlightFr: 'Présence digitale complète et campagnes publicitaires ciblées boostant les ventes en ligne.',
    highlightEn: 'Integrated digital presence and targeted advertising driving rapid e-commerce sales growth.',
    metrics: '+170% تفاعل • 300% ROAS',
    publishedAt: '2024-09-15',
  },
  {
    id: 19,
    slug: 'creche-btissam',
    title: 'Crèche Btissam',
    category: 'marketing',
    categoryLabelAr: 'هوية وتسويق',
    categoryLabelFr: 'Branding & Marketing',
    categoryLabelEn: 'Branding & Marketing',
    img: '/assets/agency/creche-btissam.jpg',
    tags: ['Branding', 'Social Media', 'Content', 'Advertising'],
    highlightAr: 'تطوير الهوية البصرية وإطلاق حملات إعلانية لاستقطاب أولياء الأمور وزيادة التسجيلات.',
    highlightFr: 'Identité visuelle, stratégie réseaux sociaux et campagnes d’acquisition pour crèche.',
    highlightEn: 'Visual branding, social media setup, and targeted campaigns driving student enrollments.',
    metrics: '+230% استفسارات • +90% تسجيلات',
    publishedAt: '2024-09-10',
  },
  {
    id: 18,
    slug: 'hanae-kandri',
    title: 'Psychologue Hanae Kandri',
    category: 'marketing',
    categoryLabelAr: 'حضور رقمي وتواصل',
    categoryLabelFr: 'Présence Digitale & Médias',
    categoryLabelEn: 'Digital Presence & Media',
    img: '/assets/agency/hanae-kandri.jpg',
    tags: ['Digital Presence', 'Branding', 'Lead Generation'],
    highlightAr: 'بناء الحضور الرقمي المهني لعيادة نفسية واستقطاب الاستشارات وتسهيل التواصل.',
    highlightFr: 'Développement de la présence digitale professionnelle et acquisition de consultations.',
    highlightEn: 'Professional digital presence architecture and patient appointment lead acquisition.',
    metrics: '+180% وصول • 2.5x حجوزات',
    publishedAt: '2024-09-01',
  },
  {
    id: 17,
    slug: 'horizon-travel',
    title: "Horizon Travel's Morocco",
    category: 'marketing',
    categoryLabelAr: 'تسويق سياحي ومحتوى',
    categoryLabelFr: 'Marketing Touristique',
    categoryLabelEn: 'Travel Marketing',
    img: '/assets/agency/horizon-travel.jpg',
    tags: ['Digital Strategy', 'Content', 'Advertising'],
    highlightAr: 'حملات تسويقية سياحية ومحتوى ترويجي لاستقطاب السياح وتنظيم الرحلات السياحية.',
    highlightFr: 'Campagnes marketing touristiques et production de contenu promotionnel attractif.',
    highlightEn: 'Tourism marketing campaigns and visual storytelling driving tour bookings.',
    metrics: '+210% استفسارات رحلات',
    publishedAt: '2024-08-20',
  },
  {
    id: 16,
    slug: 'mangeo-app',
    title: 'Mangeo App',
    category: 'web',
    categoryLabelAr: 'منصات سحابية وتجارة',
    categoryLabelFr: 'Plateformes SaaS & E-commerce',
    categoryLabelEn: 'SaaS & E-commerce Platform',
    img: '/assets/agency/mangeo-mockup.jpg',
    tags: ['Website', 'Automation', 'E-commerce', 'Branding'],
    highlightAr: 'منصة سحابية متكاملة لإدارة وتشغيل التجارة الإلكترونية بنظام الدفع عند الاستلام والأتمتة.',
    highlightFr: 'Plateforme SaaS tout-en-un pour la gestion et l’automatisation du e-commerce COD.',
    highlightEn: 'All-in-one SaaS platform for Cash on Delivery e-commerce operations & automation.',
    metrics: 'SaaS متكامل • أتمتة شاملة',
    publishedAt: '2024-08-15',
  },
  {
    id: 15,
    slug: 'vanora',
    title: 'Vanora.ma',
    category: 'web',
    categoryLabelAr: 'متاجر إلكترونية فاخرة',
    categoryLabelFr: 'Boutique E-commerce Luxe',
    categoryLabelEn: 'Luxury E-commerce',
    img: '/assets/agency/vanora.jpg',
    tags: ['E-commerce', 'Website', 'Branding', 'Advertising'],
    highlightAr: 'متجر إلكتروني فاخر للعطور وتجربة تسوق متطورة رفعت معدل التحويل والمبيعات.',
    highlightFr: 'Boutique e-commerce haut de gamme et identité visuelle pour marque de parfumerie.',
    highlightEn: 'Luxury perfume e-commerce storefront with high-converting buyer UX and digital branding.',
    metrics: '+220% نمو التحويلات',
    publishedAt: '2024-08-05',
  },
  {
    id: 14,
    slug: 'mohammed-tifawine',
    title: 'Mohammed Tifawine',
    category: 'music',
    categoryLabelAr: 'إدارة فنية ومحتوى',
    categoryLabelFr: 'Production & Médias',
    categoryLabelEn: 'Production & Media',
    img: '/assets/agency/tifawine-mockup.jpg',
    tags: ['Content', 'Branding', 'Social Media'],
    highlightAr: 'إدارة وتطوير الحضور الفني الرقمي وإطلاق الإصدارات الموسيقية عبر اليوتيوب والمنصات.',
    highlightFr: 'Gestion de présence artistique digitale et diffusion de releases musicales sur YouTube.',
    highlightEn: 'Digital artist branding, releases management, and streaming media distribution.',
    publishedAt: '2024-07-28',
  },
  {
    id: 13,
    slug: 'ifolki',
    title: 'Ifolki.ma',
    category: 'web',
    categoryLabelAr: 'مواقع وتجارة إلكترونية',
    categoryLabelFr: 'Web & E-commerce',
    categoryLabelEn: 'Web & E-commerce',
    img: '/assets/agency/ifolki.png',
    tags: ['Website', 'E-commerce', 'Landing Pages'],
    highlightAr: 'تطوير متجر إلكتروني متكامل بتصميم عصري وتجربة شراء سلسة وسريعة.',
    highlightFr: 'Développement de boutique en ligne moderne et optimisée pour la conversion rapide.',
    highlightEn: 'High-speed modern e-commerce storefront with optimized conversion funnel.',
    publishedAt: '2024-07-15',
  },
  {
    id: 12,
    slug: 'africha-oued-eddahab',
    title: 'Africha Oued Eddahab',
    category: 'marketing',
    categoryLabelAr: 'هوية وتسويق',
    categoryLabelFr: 'Identité & Marketing',
    categoryLabelEn: 'Branding & Marketing',
    img: '/assets/agency/africha-oued-eddahab.jpg',
    tags: ['Branding', 'Social Media', 'Advertising'],
    highlightAr: 'هوية بصرية وحملات ترويجية لعلامة المفروشات والأثاث المنزلي.',
    highlightFr: 'Identité visuelle et campagnes publicitaires pour marque d’ameublement.',
    highlightEn: 'Visual branding and targeted marketing campaigns for home furniture brand.',
    publishedAt: '2024-07-01',
  },
  {
    id: 11,
    slug: 'cabinet-dentaire',
    title: 'Cabinet Dentaire Dr. Mohamed Larhmaid',
    category: 'marketing',
    categoryLabelAr: 'حضور رقمي مهني',
    categoryLabelFr: 'Présence Digitale Médicale',
    categoryLabelEn: 'Medical Digital Presence',
    img: '/assets/agency/cabinet-dentaire.jpg',
    tags: ['Branding', 'Digital Presence', 'Social Media'],
    highlightAr: 'تأسيس الحضور الرقمي لعيادة طب وجراحة الأسنان وبناء الثقة الرقمية مع المرضى.',
    highlightFr: 'Création de présence digitale pour cabinet dentaire et acquisition de patients.',
    highlightEn: 'Digital presence setup and patient engagement for dental clinic.',
    publishedAt: '2024-06-20',
  },
  {
    id: 10,
    slug: 'salon-juudiey',
    title: 'Salon Juudiey',
    category: 'marketing',
    categoryLabelAr: 'هوية وتسويق محلي',
    categoryLabelFr: 'Branding & Réseaux Sociaux',
    categoryLabelEn: 'Branding & Social Media',
    img: '/assets/agency/salon-juudiey.jpg',
    tags: ['Branding', 'Social Media', 'Advertising'],
    highlightAr: 'تصميم هوية بصرية وإدارة التواصل الاجتماعي والحملات لصالون تجميل راقٍ.',
    highlightFr: 'Identité visuelle et gestion des réseaux sociaux pour salon de beauté premium.',
    highlightEn: 'Visual branding, content creation, and local acquisition campaigns for beauty salon.',
    publishedAt: '2024-06-10',
  },
  {
    id: 9,
    slug: 'gama-pro',
    title: 'Gama Pro',
    category: 'marketing',
    categoryLabelAr: 'هوية تجارية وإعلانات',
    categoryLabelFr: 'Identité & Publicité',
    categoryLabelEn: 'Branding & Advertising',
    img: '/assets/agency/gama-pro.jpg',
    tags: ['Branding', 'Advertising', 'Content'],
    highlightAr: 'هوية تجارية متكاملة وحملات إعلانية احترافية لإطلاق العلامة التجارية.',
    highlightFr: 'Identité de marque complète et campagnes publicitaires ciblées.',
    highlightEn: 'Comprehensive corporate identity and targeted performance advertising.',
    publishedAt: '2024-05-25',
  },
  {
    id: 8,
    slug: 'ss-lavage',
    title: 'SS Lavage',
    category: 'marketing',
    categoryLabelAr: 'هوية وتسويق محلي',
    categoryLabelFr: 'Branding & Local Ads',
    categoryLabelEn: 'Branding & Local Ads',
    img: '/assets/agency/ss-lavage.jpg',
    tags: ['Branding', 'Social Media'],
    highlightAr: 'هوية بصرية وإعلانات موجهة لخدمات غسيل وتلميع وحماية السيارات.',
    highlightFr: 'Identité de marque et acquisition locale pour centre de lavage automobile.',
    highlightEn: 'Brand identity and localized promotional campaigns for automotive care center.',
    publishedAt: '2024-05-15',
  },
  {
    id: 7,
    slug: 'ecole-sennouni',
    title: 'Ecole Sennouni Science School',
    category: 'marketing',
    categoryLabelAr: 'هوية وحملات تسجيل',
    categoryLabelFr: 'Identité & Inscriptions',
    categoryLabelEn: 'Branding & Admissions',
    img: '/assets/agency/ecole-sennouni.jpg',
    tags: ['Branding', 'Content', 'Advertising'],
    highlightAr: 'إطلاق الهوية البصرية وحملات التسجيل للمؤسسة التعليمية الخاصة.',
    highlightFr: 'Identité visuelle et campagnes digitales d’inscriptions scolaires.',
    highlightEn: 'Visual branding and admissions campaigns for private science school.',
    publishedAt: '2024-05-01',
  },
];

/**
 * Returns the latest published projects, sorted by date descending.
 */
export function getLatestProjects(limit = 3): PortfolioProject[] {
  return [...portfolioProjects]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit);
}
